### ISSUE TITLE
Can't run it

### ISSUE THREAD

**Issue by aktary** [WhoSoup/pegnet-api-priority#1]
Trying to compile & run from source on MacOS.  Getting:

```2020/04/15 11:26:31 App shut down with error: invalid character 'e' looking for beginning of value```

**Comment by WhoSoup** [comment]
What's your `defaultconfig.ini` setting for FactomdLocation?

You can try setting `FactomdLocation="http://courtesy-node.factom.com"` and see if that works better.

**Comment by aktary** [comment]
`FactomdLocation="https://api.factomd.net/v2"`
was what I had... but changing it to http://courtesy-node.factom.com made a difference!  It's running now.... I think.  Will let you know when/if that changes ;)

**Comment by WhoSoup** [comment]
> `FactomdLocation="https://api.factomd.net/v2"` was what I had...

Ah, you need to remove the "/v2" part at the end

**Comment by aktary** [comment]
That's a bummer, given this is what they say you should copy:

![image](https://user-images.githubusercontent.com/6234384/79419853-3e3c4c00-7f7d-11ea-863f-323db3a1b014.png)

**Comment by WhoSoup** [comment]
That's an unfortunate situation. There are two different clients floating around in the Factom ecopshere. One requires the /v2 at the end, the older one pegnet uses does not.

I'll make a note in the README
